[package]
authors = ["Sebastian Humenda <shumenda@gmx.de>"]
build = "build.rs"
description = "Efficient, static lookup table for ISO 639 language codes"
documentation = "https://docs.rs/isolang"
keywords = [
    "iso",
    "language",
    "language-code",
    "autonym"
]
license = "Apache-2.0"
name = "isolang"
readme = "README.md"
repository = "https://github.com/humenda/isolang-rs"
version = "2.0.0"
edition = "2018"

[build-dependencies]
phf_codegen = "0.10"

[dependencies]
phf = "0.10.0"

[dependencies.serde]
optional = true
version = "1.0"


[features]
default = ["english_names"]
english_names = []
local_names = []
serde_serialize = [
    "serde",
]

[dev-dependencies]
serde_json = "1.0"
